### ISSUE TITLE
Refactoring to TutorHelper context

### ISSUE THREAD

**Issue by lywjoel** [CS2103-AY1819S1-W13-4/main#162]
[Done] Rename AppendSyll / EraseSyll to AddSyll / DeleteSyll (and all instances elsewhere)
[Done] Rename Person to Student (and all instances elsewhere)
[Done] Rename seedu.address to tutorhelper (and all instances elsewhere)

After the above is completed,
Update UserGuide.adoc
Update Help Page

**Comment by ghost** [comment]
Update: every file inside src/main has its javadoc updated.
