### ISSUE TITLE
Some Commands do not refresh UI

### ISSUE THREAD

**Issue by lywjoel** [CS2103-AY1819S1-W13-4/main#219]
addsyll
deletesyll
editsyll
undo
redo

**Comment by ghost** [comment]
The syllabus commands do not raise event _StudentPanelSelectionChangedEvent_, hence the UI is not updated. 

This is because when any syllabus is changed, the Student himself it is not changed (Student still has all of his attributes and pointers unmodified). Hence it does not raise the event.
