### ISSUE TITLE
Undefined behavior in addsub command

### ISSUE THREAD

**Issue by andlimey** [CS2103-AY1819S1-W13-4/main#232]
![image](https://user-images.githubusercontent.com/34736022/48299596-1637f600-e50a-11e8-8ac6-4fe12a476a68.png)

Putting two subjects in one `s/` prefix is not allowed and no error message is thrown.

![image](https://user-images.githubusercontent.com/34736022/48299629-b3932a00-e50a-11e8-87b5-573f306d53ee.png)
![image](https://user-images.githubusercontent.com/34736022/48299631-b857de00-e50a-11e8-8591-d2e3b5b5396d.png)

Passing `s/History s/Literature` only adds Literature to the Student's list of subjects

**Comment by ghost** [comment]
Restricted subject keyword to only one word to solve the issue `s/History Literature`. Error message of invalid subject will be shown instead.
