### ISSUE TITLE
When user key in value greater than Integer.Max_Value, error message shows invalid command format instead of invalid subject index etc

### ISSUE THREAD

**Issue by ooihuiying** [CS2103-AY1819S1-W13-4/main#233]
![image](https://user-images.githubusercontent.com/40648338/48299838-f73b6300-e50d-11e8-9d64-883ce5eae30b.png)
![image](https://user-images.githubusercontent.com/40648338/48299840-015d6180-e50e-11e8-8c9b-e98f15699a90.png)

**Comment by ghost** [comment]
Added index limit to the UserGuide.
