### ISSUE TITLE
When user key in more than 1 sy/, addsyll does not throw an error. Even though as seen in the image below, hello and integration were already present the command doesn't throw an error. Banana which is the only new sy is added successfully. Not a major bug though..

### ISSUE THREAD

**Issue by ooihuiying** [CS2103-AY1819S1-W13-4/main#234]
![image](https://user-images.githubusercontent.com/40648338/48299951-a9bff580-e50f-11e8-8cb7-fac1a39c8c48.png)

**Comment by ghost** [comment]
Changed current implementation to explicitly allow the addition of multiple syllabuses at once. If any of them are duplicates of content, an error message will be thrown.
