### ISSUE TITLE
Same issue as addsyll command for Integer.Max_Value

### ISSUE THREAD

**Issue by ooihuiying** [CS2103-AY1819S1-W13-4/main#235]
![image](https://user-images.githubusercontent.com/40648338/48300000-310d6900-e510-11e8-92b2-4bec390190dd.png)
![image](https://user-images.githubusercontent.com/40648338/48300008-5dc18080-e510-11e8-972f-3c733a444d16.png)

**Comment by ooihuiying** [comment]
Mark command also has same issue.

**Comment by ghost** [comment]
Added index limit into the UserGuide.
