### ISSUE TITLE
When user chains commands it continues takes the last added command

### ISSUE THREAD

**Issue by ongyz** [CS2103-AY1819S1-W13-4/main#238]
Two add commands back to back. System seems to be registering the second add command.

![image](https://user-images.githubusercontent.com/33322048/48300172-da099300-e513-11e8-9e3d-3e751acc1e40.png)

Changing name of student to add. Verifies that command is following the command appended at the back.
![image](https://user-images.githubusercontent.com/33322048/48300182-03c2ba00-e514-11e8-979d-ef02612f6f9a.png)

**Comment by ongyz** [comment]
1. Made fixed edition where only fix prefix is taken not multiple
2. Prefixes that allow multiple input now split by `,`
3. Identified addsyll/editsyll has the same bug, commands that use prefixes have this bug

![image](https://user-images.githubusercontent.com/33322048/48301905-cf5cf700-e52f-11e8-9cc6-4b6c82b7603d.png)

**Comment by ongyz** [comment]
1. Fix syllabus command chain errors by adding a max length to syllabus entries, max allowable 30 characters

**Comment by lywjoel** [comment]
i think alternatively we can also check for illegal characters in the syllabus like "/"
